## Pandas e Excel

%pip install openpyxl

In [1]:
import pandas as pd

In [2]:
# apro un file excel da pandas
dfp = pd.read_excel("persone.xlsx")
dfp

       nome  cognome data_nascita  peso  altezza
0     Mario    Rossi   01/01/1980    75      178
1     Maria    Verdi   15/03/1992    60      165
2  Giovanni      Blu   22/07/1975    80      182
3      Anna     Neri   05/11/1998    55      160
4      Luca  Bianchi   18/04/1963    90      175
5      Sara   Gialli   29/12/2000    48      158
6    Davide    Viola   10/08/1987    72      180
7     Elena     Rosa   03/02/1978    65      168
8     Marco  Marroni   17/06/1995    78      183
9  Beatrice  Azzurri   24/09/2002    52      155

In [3]:
import numpy as np

# genero una lista di mesi
mesi = ["ge", 'fe', 'ma', 'ap', 'mg', 'gi', 'lu', 'ag', 'st', 'ot', 'nv', 'di']

#genero dei valori casuali per simulare i movimenti in ingresso/uscita di un conto corrente
ingressi = np.random.randint(1000, 5000, size=12)
uscite = np.random.randint(1000, 5000, size=12)

#creo il dataframe
cc = pd.DataFrame( {'mese':mesi, "entrate":ingressi, "uscite":uscite} )
cc

   mese  entrate  uscite
0    ge     2108    1788
1    fe     4860    1365
2    ma     1608    3642
3    ap     2390    4111
4    mg     2169    4866
5    gi     3617    2937
6    lu     2358    2667
7    ag     1613    3012
8    st     4036    4123
9    ot     1365    1047
10   nv     1115    1243
11   di     1909    4309

In [ ]:
# %pip install xlsxwriter

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
wr = pd.ExcelWriter("conto.xlsx", engine='xlsxwriter')
cc.to_excel(wr, index=False, sheet_name="conto")
#operazioni sul file excel
wr.close()

In [9]:
with pd.ExcelWriter("conto2.xlsx", engine='xlsxwriter') as wr:
    cc.to_excel(wr, index=False, sheet_name="conto")

    # wr.book mi permette di lavorare sul modello del file excel
    workbook = wr.book
    #seleziono il tab del mio foglio excel
    ws = wr.sheets['conto']
    #modifico una cella
    f1 = workbook.add_format({'bold':True, 'font_color':'blue'})
    ws.write("D2", "Hello!", f1)

## Pandas e Database

Consigliato accesso con https://www.sqlalchemy.org/

In [ ]:
# %pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\paolo\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\paolo\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\paolo\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine
#creo la connessione al database e nel caso lo crea
eng = create_engine('sqlite:///banca.db')
# trasferisce il dataframe in una tabella
cc.to_sql('conto', eng, index=False)

12

In [13]:
#lettura dati da una tabella
with eng.connect() as c:
    df2 = pd.read_sql_table("conto", c)

df2.head()

  mese  entrate  uscite
0   ge     2108    1788
1   fe     4860    1365
2   ma     1608    3642
3   ap     2390    4111
4   mg     2169    4866

In [14]:
with eng.connect() as c:
    df3 = pd.read_sql_query("SELECT * FROM conto WHERE entrate > 2500", c)

df3

  mese  entrate  uscite
0   fe     4860    1365
1   gi     3617    2937
2   st     4036    4123

In [ ]:
#chiude la conenssione al file
eng.dispose()

In [16]:
#per cancellare il file
import os
os.remove("banca.db")