### Report Vendite

In [1]:
import pandas as pd

In [2]:
#importo i clienti
dfcu = pd.read_csv("T02-eCommerce-CustomerMD.csv", delimiter=";")
dfcu.head()

   Customer_ID         Country
0        12346  United Kingdom
1        12347         Iceland
2        12348         Finland
3        12349           Italy
4        12350          Norway

In [3]:
dfcu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5856 entries, 0 to 5855
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5856 non-null   int64
 1   Country      5856 non-null   object
dtypes: int64(1), object(1)
memory usage: 91.6+ KB

In [5]:
dfpr = pd.read_csv("T02-eCommerce-ProductMD.csv", delimiter=",", encoding="latin-1")
dfpr.head()

  StockCode              Description    Category         Subcategory
0    10002R    ROBOT PENCIL SHARPNER  Stationery  Desktop Stationery
1     10109     BENDY COLOUR PENCILS  Stationery  Desktop Stationery
2     10120             DOGGY RUBBER  Stationery  Desktop Stationery
3    10123C    HEARTS WRAPPING TAPE   Stationery  Desktop Stationery
4    10123G  ARMY CAMO WRAPPING TAPE  Stationery  Desktop Stationery

In [6]:
dfpr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3812 entries, 0 to 3811
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StockCode    3812 non-null   object
 1   Description  3812 non-null   object
 2   Category     3812 non-null   object
 3   Subcategory  3812 non-null   object
dtypes: object(4)
memory usage: 119.3+ KB

In [7]:
dftr = pd.read_excel("T02-eCommerce-TransactionsL3M.xlsx", engine="openpyxl")
dftr.head()

c:\Users\paolo\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Invoice StockCode  Quantity  Price  Customer_ID       Invoice_time
0  565080     20677         8   1.25        13509  D01/9/19T08:25:00
1  565080     22128        24   1.25        13509  D01/9/19T08:25:00
2  565082     22423         2  12.75        13305  D01/9/19T09:15:00
3  565082    15060B         8   3.75        13305  D01/9/19T09:15:00
4  565082     23245         4   4.95        13305  D01/9/19T09:15:00

In [8]:
dftr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130287 entries, 0 to 130286
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       130287 non-null  object
 1   StockCode     130287 non-null  object
 2   Quantity      130287 non-null  int64
 3   Price         130287 non-null  float64
 4   Customer_ID   130287 non-null  int64
 5   Invoice_time  130287 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 6.0+ MB

In [9]:
dftrh = pd.read_excel("T02-eCommerce-TransactionsHistory.xlsx", engine="openpyxl")
dftrh.head()

c:\Users\paolo\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Invoice StockCode  Quantity  Price  Customer_ID        Invoice_time
0  489434     85048        12   6.95        13085  D01/12/17T07:45:00
1  489434    79323P        12   6.75        13085  D01/12/17T07:45:00
2  489434    79323W        12   6.75        13085  D01/12/17T07:45:00
3  489434     22041        48   2.10        13085  D01/12/17T07:45:00
4  489434     21232        24   1.25        13085  D01/12/17T07:45:00

In [10]:
dftrh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545592 entries, 0 to 545591
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       545592 non-null  object
 1   StockCode     545592 non-null  object
 2   Quantity      545592 non-null  int64
 3   Price         545592 non-null  float64
 4   Customer_ID   545592 non-null  int64
 5   Invoice_time  545592 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 25.0+ MB

In [11]:
df_tot = pd.concat([dftr, dftrh], ignore_index=True, sort=False)
df_tot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675879 entries, 0 to 675878
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       675879 non-null  object
 1   StockCode     675879 non-null  object
 2   Quantity      675879 non-null  int64
 3   Price         675879 non-null  float64
 4   Customer_ID   675879 non-null  int64
 5   Invoice_time  675879 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 30.9+ MB